// Generates src/globe/regionLayout.ts: the canonical layout of 7 provinces and 49 city
// areas inside a regular hexagonal state, chosen so that all 49 city areas have the
// same area.
//
// Frame: the state is a regular hexagon with inradius 1 whose neighbours lie at
// distance 2 in the directions 0°, 60°, … 300°. Provinces follow the aperture-7 rule
// (a centre and a ring of six at 2/√7, turned 19.1°); in a regular hexagon their
// nested Voronoi cells already have equal areas. Each province's 7 city areas start
// the same way inside the province, then
//   1. Lloyd relaxation moves every city to the centroid of its cell, and
//   2. area balancing moves a city away from a sibling neighbour whose cell is smaller,
//      which shifts their shared bisector toward the larger cell,
// until all 49 cells have the same area. Areas are measured on a fine point sample.
//
// Usage: node scripts/region-layout.mjs   (rewrites src/globe/regionLayout.ts)
import fs from 'node:fs';

const RING = 2 / Math.sqrt(7);
const TWIST = Math.atan(Math.sqrt(3) / 5);
const ringPoint = (k, r) => {
  const a = TWIST + ((k - 1) * Math.PI) / 3;
  return [r * Math.cos(a), r * Math.sin(a)];
};
const provinces = [[0, 0], ...[1, 2, 3, 4, 5, 6].map(k => ringPoint(k, RING))];

const inState = (x, y) => [0, 1, 2, 3, 4, 5].every(k => x * Math.cos((k * Math.PI) / 3) + y * Math.sin((k * Math.PI) / 3) <= 1);
const nearest = (x, y, list, from, n) => {
  let best = from;
  let bestD = Infinity;
  for (let i = from; i < from + n; i++) {
    const d = (x - list[i][0]) ** 2 + (y - list[i][1]) ** 2;
    if (d < bestD) { bestD = d; best = i; }
  }
  return best;
};

const samples = [];
const STEP = 0.004;
for (let y = -1.2; y <= 1.2; y += STEP * 0.866) for (let x = -1.2; x <= 1.2; x += STEP) if (inState(x, y)) samples.push([x, y]);
const provinceOf = samples.map(([x, y]) => nearest(x, y, provinces, 0, 7));

// Start: the aperture-7 rule inside each province, turned toward the state centre
const provinceIn = 1 / Math.sqrt(7);
const cities = [];
provinces.forEach(([px, py], p) => {
  const [rx, ry] = p === 0 ? [1, 0] : [-px / Math.hypot(px, py), -py / Math.hypot(px, py)];
  for (let k = 0; k < 7; k++) {
    const [u, v] = k === 0 ? [0, 0] : ringPoint(k, RING * provinceIn);
    cities.push([px + u * rx - v * ry, py + u * ry + v * rx]);
  }
});

const cells = () => {
  const n = new Array(49).fill(0), sx = new Array(49).fill(0), sy = new Array(49).fill(0);
  samples.forEach(([x, y], i) => {
    const c = nearest(x, y, cities, provinceOf[i] * 7, 7);
    n[c]++; sx[c] += x; sy[c] += y;
  });
  return { area: n.map(v => (v / samples.length) * 49), cx: sx.map((s, c) => s / n[c]), cy: sy.map((s, c) => s / n[c]) };
};
const spread = a => `${Math.min(...a).toFixed(3)}–${Math.max(...a).toFixed(3)}`;

console.log('start areas', spread(cells().area));
for (let it = 0; it < 60; it++) {
  const { cx, cy } = cells();
  cities.forEach((c, i) => { c[0] = cx[i]; c[1] = cy[i]; });
}
console.log('after Lloyd', spread(cells().area));
for (let it = 0; it < 200; it++) {
  const { area } = cells();
  const moves = cities.map(() => [0, 0]);
  for (let p = 0; p < 7; p++) {
    for (let i = p * 7; i < p * 7 + 7; i++) {
      for (let j = p * 7; j < p * 7 + 7; j++) {
        const dx = cities[j][0] - cities[i][0], dy = cities[j][1] - cities[i][1], d = Math.hypot(dx, dy);
        if (i === j || d > 0.45) continue; // sibling neighbours only
        const k = (0.02 * (area[i] - area[j])) / d;
        moves[i][0] -= k * dx;
        moves[i][1] -= k * dy;
      }
    }
  }
  cities.forEach((c, i) => { c[0] += moves[i][0]; c[1] += moves[i][1]; });
}
const final = cells().area;
console.log('after balancing', spread(final));

const fmt = list => list.map(([x, y]) => `  [${x.toFixed(6)}, ${y.toFixed(6)}],`).join('\n');
fs.writeFileSync(new URL('../src/globe/regionLayout.ts', import.meta.url), `/**
 * regionLayout.ts — GENERATED by scripts/region-layout.mjs, do not edit.
 *
 * Canonical layout inside a regular hexagonal state with inradius 1 whose neighbours
 * lie at distance 2 in the directions 0°, 60°, … 300°. Provinces follow the aperture-7
 * rule; city areas (7 per province, province p owns p*7 … p*7+6) are relaxed so that
 * all 49 nested Voronoi cells have the same area (spread ${spread(final)} of the mean).
 */
export const PROVINCE_LAYOUT: readonly [number, number][] = [
${fmt(provinces)}
];

export const CITY_LAYOUT: readonly [number, number][] = [
${fmt(cities)}
];
`);
console.log('wrote src/globe/regionLayout.ts');
